### ISSUE TITLE
Hope to add simplified Chinese translation

### ISSUE THREAD

**Issue by Gaoyifei1011** [iridescentkiwi/FluentAbout#4]
希望能添加简体中文的版本翻译 
Hope to add simplified Chinese translation.

这个文档是我翻译后的内容，图片是简体中文操作系统上的具体内容。 
This document is my translated content, the picture is the specific content on the simplified Chinese operating system.
[Translation.Document.docx](https://github.com/VOLKANOGEDAY/FluentAbout/files/10456667/Translation.Document.docx)

其他问题
1. Hope to upgrade to Windows App SDK version 1.2 as soon as possible and add IL clipping support (greatly reducing the size of the installation package).
希望能尽快升级到Windows 应用 SDK 1.2版本，并添加IL裁剪支持。

2.您是否忘记了为应用程序添加logo图标？
Have you forgotten to add a logo icon to your app?
![image](https://user-images.githubusercontent.com/49179966/213442562-19bf4575-823b-43ea-9d48-e76e5586099e.png)

**Comment by iridescentkiwi** [comment]
Hi,
Firstly, as I mentioned in readme, the app is discontinued since I switched to Linux. However, you can clone the repository, duplicate turkish translation folder, add your own translations and recompile the app.
Secondly, as it is a WinAppSDK app which was intended to work as a package, the app executable doesn't have an icon although when you launch the app after installing (which is the intended way for UWP and WinAppSDK apps), the app icon persists.
